### ISSUE TITLE
Direct Link

### ISSUE THREAD

**Issue by crakhead43** [jaykali/lockphish#1]
I don't get any direct link
![image](https://user-images.githubusercontent.com/68694268/88449765-bdf07700-ce06-11ea-93e8-f3615e28c44f.png)

**Comment by jaykali** [comment]
Check your internet connection or re-install this tool.

**Comment by TheRicky90** [comment]
i faced the same issue in nethunter kali rom for android.. 
if i start in a separate terminal ngrok http 80 your tool will take the same link generated from ngrok tab.. but wen i whant to connect is an error 502 bad gateway on ngrok.. i asked me te port number wo this tool use as default?
