### ISSUE TITLE
Link failed 

### ISSUE THREAD

**Issue by raedbsili1991** [jaykali/lockphish#11]
Hi, why there is no generated link ? 
![Screenshot_2021-01-24-01-48-37-57_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/31764213/105618357-7c0cb180-5de6-11eb-9a6a-6fe207aba3cd.jpg)

**Comment by Hax4us** [comment]
just Turn **ON** your Android's **Hotspot** before executing it.

**Comment by jaykali** [comment]
Thanks @Hax4us , Now closing it. This will solve your problem @raedbsili1991
