### ISSUE TITLE
can't find ngrok link

### ISSUE THREAD

**Issue by dark8960** [jaykali/lockphish#12]
![Screenshot_20210202-121056__01](https://user-images.githubusercontent.com/16070378/106551328-f4dedc80-654f-11eb-9b1f-ab3ead50ad86.jpg)

**Comment by jaykali** [comment]
You need to turn on hotspot. Now new exit termux and use mobile data and turn on hotspot. Then run LockPhish again. Thanks

**Comment by dark8960** [comment]
I solved the problem after replacing ngrok，thanks

**Comment by meddyCv** [comment]
> I solved the problem after replacing ngrok，thanks

How
