### ISSUE TITLE
error help !!

### ISSUE THREAD

**Issue by ghost** [jaykali/lockphish#13]
Sorry, maybe I'm doing something wrong because no URL..
![Screenshot_2021-02-23-13-11-24-911_com termux](https://user-images.githubusercontent.com/75779087/108835957-e5940180-75d8-11eb-8a35-884950f40c9b.jpg)

**Comment by jaykali** [comment]
#12 This is solved here

**Comment by ghost** [comment]
> [# 12](https://github.com/jaykali/lockphish/issues/12) Тут це вирішено

thank you
