### ISSUE TITLE
sleep: cannot read realtime clock: Invalid argument

### ISSUE THREAD

**Issue by Pavelpikola** [jaykali/lockphish#2]
Hi, 
i have error, everything is ok, but when i write site like www.facebook.com or www.youtube.com and hit enter i have only thousand of: 

sleep: cannot read realtime clock: Invalid argument
sleep: cannot read realtime clock: Invalid argument
sleep: cannot read realtime clock: Invalid argument
sleep: cannot read realtime clock: Invalid argument
what can i do?

**Comment by jaykali** [comment]
Are you using WSL(Windows Subsystem for Linux) to install Kali? This error comes in WSL installation. You can check [this](https://malware-guide.com/blog/ubuntu-20-04-lts-for-windows-10-is-available-for-download)
