### ISSUE TITLE
There are no links in "Direct Link" 

### ISSUE THREAD

**Issue by RZXX1** [jaykali/lockphish#26]
Redirect after phishing (Default: Youtube ):

[+] Starting php server...
[+] Starting ngrok server...
[+] Building webpages
[+] Direct link:

[*] Waiting targets, Press Ctrl + C to exit...

**Comment by jaykali** [comment]
This tool requires updates, not working properly. But one thing if you are on Android then try turning on your WiFi hotspot then try this tool. Thanks.
