### ISSUE TITLE
link wont generate

### ISSUE THREAD

**Issue by walterwhite0318** [jaykali/lockphish#5]
![Screen Shot 2020-09-21 at 13 26 34](https://user-images.githubusercontent.com/70662378/93762328-a28bc780-fc0f-11ea-8347-54f74fa75119.png)
please help im on macOS

**Comment by jaykali** [comment]
Yes, the default macOS base64 implementation doesn't have the `-w` flag.
The flag is called `-b` in macOS, and it already defaults to 0, which means base64 in macOS has the same behaviour as base64 `-w0` on Linux.

You need to modify a little bit on the script, or you should try it from Kali Linux.

Thanks.

**Comment by Cipherx7** [comment]
You should turn on mobile hospot
