### ISSUE TITLE
error line

### ISSUE THREAD

**Issue by Andr3ix** [jaykali/lockphish#7]
lockphish.sh: línea 160: curl: orden no encontrada
lockphish.sh: línea 176: curl: orden no encontrada
![Captura de pantalla de 2021-01-04 14-42-33](https://user-images.githubusercontent.com/76051133/103572854-3faafd00-4e9b-11eb-901a-bb8bf2fa9bb2.png)

**Comment by Andr3ix** [comment]
oh i figured out the solution i had to set the authtoken in cd lockphsih / before using.

**Comment by Andr3ix** [comment]
not working again with solution, same error.

**Comment by jaykali** [comment]
curl is missing on your system? Have you tried `sudo apt install curl` ?

**Comment by Andr3ix** [comment]
no, I checked the lockphish.sh file to see the error lines and I realized that that was missing thank you very much anyway.
